import CryptoKit
import Foundation
import SwiftData

struct CapturedClip: Equatable {
    let contentType: ContentType
    let rawData: Data
    let textContent: String?
    let contentHash: String
}

/// Builds a clip from what the iPhone read off its pasteboard. Mirrors the Mac's `ContentTypeClassifier`
/// and `ClipboardMonitor` byte for byte, so the same content gets the same `contentHash` on both devices.
enum ClipCapture {
    /// Pasteboard types that password managers and apps set on copies that must not be saved.
    /// Mirrors the skip rules in the Mac's `ContentTypeClassifier`.
    static let skippedPasteboardTypes = [
        "org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType", "org.nspasteboard.AutoGeneratedType"]

    static func text(_ text: String) -> CapturedClip? {
        guard !text.isEmpty else { return nil }
        let data = Data(text.utf8)
        // Mac rule: text that parses as a URL with both a scheme and a host is a link.
        let isLink = URL(string: text).map { $0.scheme != nil && $0.host != nil } ?? false
        return CapturedClip(contentType: isLink ? .url : .plainText, rawData: data, textContent: text, contentHash: hash(data))
    }

    static func image(_ data: Data) -> CapturedClip? {
        guard !data.isEmpty else { return nil }
        return CapturedClip(contentType: .image, rawData: data, textContent: nil, contentHash: hash(data))
    }

    /// Lowercase hex SHA-256, the format `ClipboardMonitor` stores.
    static func hash(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    /// Mac rule (`ClipboardMonitor.isDuplicate`): the same hash copied in the last 10 s is not captured again.
    static func isRecentDuplicate(hash: String, in context: ModelContext, now: Date) throws -> Bool {
        let cutoff = now.addingTimeInterval(-10)
        let recent = FetchDescriptor<ClipboardItem>(predicate: #Predicate { $0.contentHash == hash && $0.copiedAt > cutoff })
        return try context.fetchCount(recent) > 0
    }
}
