import AppKit
import OSLog
import UniformTypeIdentifiers

struct ContentTypeClassifier: Sendable {

    struct ClassifiedContent: Sendable {
        let contentType: ContentType
        let rawData: Data
        let textContent: String?
    }

    func classify(_ pasteboard: NSPasteboard) -> ClassifiedContent? {
        let types = pasteboard.types ?? []

        // Check for transient/concealed content (password managers, etc.)
        if types.contains(NSPasteboard.PasteboardType("org.nspasteboard.TransientType")) ||
           types.contains(NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")) ||
           types.contains(NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")) {
            return nil
        }

        // Color
        if types.contains(.color), let color = NSColor(from: pasteboard) {
            let hex = color.hexString
            if let data = hex.data(using: .utf8) {
                return ClassifiedContent(contentType: .color, rawData: data, textContent: hex)
            }
        }

        // Image
        if let imageType = types.first(where: {
            [.tiff, .png].contains($0) ||
            $0.rawValue == "public.jpeg"
        }) {
            if let data = pasteboard.data(forType: imageType) {
                return ClassifiedContent(contentType: .image, rawData: data, textContent: nil)
            }
        }

        // Files: read into a bundle that syncs. Folders, packages, unreadable or oversized files stay a local path.
        if types.contains(.fileURL),
           let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           let files = Self.readFiles(urls) {
            return files
        }

        // File URL
        if types.contains(.fileURL),
           let urlString = pasteboard.string(forType: .fileURL),
           let url = URL(string: urlString) {
            let name = url.lastPathComponent
            if let data = urlString.data(using: .utf8) {
                return ClassifiedContent(contentType: .fileURL, rawData: data, textContent: name)
            }
        }

        // URL
        if types.contains(.URL),
           let urlString = pasteboard.string(forType: .URL) {
            if let data = urlString.data(using: .utf8) {
                return ClassifiedContent(contentType: .url, rawData: data, textContent: urlString)
            }
        }

        // HTML
        if types.contains(.html),
           let html = pasteboard.string(forType: .html) {
            if let data = html.data(using: .utf8) {
                let plainText = pasteboard.string(forType: .string)
                return ClassifiedContent(contentType: .html, rawData: data, textContent: plainText ?? html)
            }
        }

        // Rich Text (RTF)
        if types.contains(.rtf),
           let data = pasteboard.data(forType: .rtf) {
            let plainText = pasteboard.string(forType: .string)
            return ClassifiedContent(contentType: .richText, rawData: data, textContent: plainText)
        }

        // Plain Text (also handles URLs pasted as text)
        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            if let data = text.data(using: .utf8) {
                // Check if text is actually a URL
                if let url = URL(string: text), url.scheme != nil, url.host != nil {
                    return ClassifiedContent(contentType: .url, rawData: data, textContent: text)
                }
                return ClassifiedContent(contentType: .plainText, rawData: data, textContent: text)
            }
        }

        return nil
    }

    private static let log = Logger(subsystem: "com.robbyfuu.copyd", category: "Capture")

    /// A `.files` clip when every URL is a local, downloaded regular file within `FileBundle`'s limits and readable,
    /// else nil. The sandbox grants pasteboard file URLs; the scoped access covers URLs that carry a security scope.
    private static func readFiles(_ urls: [URL]) -> ClassifiedContent? {
        let scoped = urls.filter { $0.startAccessingSecurityScopedResource() }
        defer { scoped.forEach { $0.stopAccessingSecurityScopedResource() } }
        let keys: Set<URLResourceKey> = [.isRegularFileKey, .fileSizeKey, .contentTypeKey,
                                         .ubiquitousItemDownloadingStatusKey, .volumeIsLocalKey]
        let values = urls.compactMap { try? $0.resourceValues(forKeys: keys) }
        let sizes = values.compactMap { $0.isRegularFile == true ? $0.fileSize : nil }
        // Never read a file that isn't downloaded from iCloud Drive or sits on a network volume.
        let local = values.allSatisfy {
            FileBundle.isLocal(downloadingStatus: $0.ubiquitousItemDownloadingStatus, volumeIsLocal: $0.volumeIsLocal)
        }
        guard sizes.count == urls.count, local, FileBundle.withinLimits(sizes: sizes) else {
            log.notice("Copied \(urls.count, privacy: .public) file(s) kept as a local file clip: folder, unreadable, not local or over the limits")
            return nil
        }
        do {
            let files = try zip(urls, values).map { url, v in
                (name: url.lastPathComponent, data: try Data(contentsOf: url, options: .mappedIfSafe),
                 uti: (v.contentType ?? .data).identifier)
            }
            return ClassifiedContent(contentType: .files, rawData: try FileBundle.encode(files),
                                     textContent: files.map(\.name).joined(separator: ", "))
        } catch {
            log.error("Copied files not readable, kept as a local file clip: \(error.localizedDescription, privacy: .public)")
            return nil
        }
    }
}

extension NSColor {
    var hexString: String {
        guard let rgb = usingColorSpace(.sRGB) else { return "#000000" }
        let r = Int(rgb.redComponent * 255)
        let g = Int(rgb.greenComponent * 255)
        let b = Int(rgb.blueComponent * 255)
        return String(format: "#%02X%02X%02X", r, g, b)
    }

    static func fromHex(_ hex: String) -> NSColor? {
        let cleaned = hex.trimmingCharacters(in: CharacterSet(charactersIn: "#"))
        guard cleaned.count == 6,
              let rgb = UInt64(cleaned, radix: 16) else { return nil }
        return NSColor(
            red: CGFloat((rgb >> 16) & 0xFF) / 255,
            green: CGFloat((rgb >> 8) & 0xFF) / 255,
            blue: CGFloat(rgb & 0xFF) / 255,
            alpha: 1.0
        )
    }
}
